# Datascience in Python course

#### Opzet datascience in Python cursus.
- installatie
- openen
- working directory
- operatoren
- variabelen
- functies
- pakketten

### <span style="color:blue">INSTALLATIE</span>
We gebruiken hiervoor Anaconda, een omvattende installer waarmee Python samen met bepaalde packages te installeren is (waaronder Jupyter Notebook) . 
[Voor installatie klik op deze link](https://www.anaconda.com/distribution/)

### <span style="color:blue"> Uitleg Kernel</span>
"Een kernel is het centrale deel van de rekenkracht, waarmee computercode in een notebook uitgevoerd wordt. Wanneer Jupyter Notebook gebruikt wordt voor het uitvoeren van python code is de kernel een specifieke python kernel, maar er zijn ook kernels beschikbaar voor vele andere programmeertalen."

In [ ]:
# Pas de programmeertaal van deze cell aan via het dashboard. 




## 1. Working directory aanpassen  

In [2]:
import os
os.getcwd()


'/Users/timo/Desktop'

In [7]:
# Pas de working directory aan met de functie os.chdir('PATH')

# os.chdir('/Users/timo/Documents/')


In [8]:
os.getcwd()


'/Users/timo/Documents'

## 2. Aritmetische operatoren

**Syntax, operatoren, functies en packages**
- De basis operatoren voor arithmetische en logische bewerkingen 

#### 2.1 Nummer optelling of aftelling

In [1]:
-1+1

# Voer zelf computaties uit

0

#### 2.2 Nummer vermenigvuldinging, deling of kwadraat

In [2]:
10 * (10**2) / 100

# Voer zelf computaties uit

10.0

#### 2.3 Nummer modulo (overblijfsel na deling) 

In [3]:
4 % 2, 5 % 3, 10 % 6

# Voer zelf computaties uit

(0, 2, 4)

## 3. Rekenen met variabelen
Tijdelijke opslag van waardes 

In [4]:
x - 1

NameError: name 'x' is not defined

In [5]:
x = 4

In [6]:
x

4

### 3.1 Variabelen overschrijven

In [7]:
x

4

In [8]:
x = 5

In [9]:
x

5

In [10]:
x = 3
x = (x+x)*x
x

18

  
### 3.2 Regels voor variabelnamen  
<span style="color: blue; font-size: 14px">naming things is hard </span>   
  
- Variabelen mogen geschreven met **letters, cijfers** en **underscore**(code-ongebruikte leestekens)  
- Variabelnamen zijn **hoofdlettergevoelig** 

**Wat werkt wel en niet**

In [11]:
haHa = 1
haHa

1

In [20]:
haha_1 = 2
haha_1

2

In [12]:
ha ha = 1

SyntaxError: invalid syntax (<ipython-input-12-1d1147e1c2ea>, line 1)

In [13]:
1d = 1

SyntaxError: invalid syntax (<ipython-input-13-d1e978804baa>, line 1)

## 4. Specifiek aan de jupyternotebook (ipython) cell
voor elke cel wordt maar één *output*,   ge- **returned**


We kunnen **wel**:  
- Meerdere operaties binnen 1 cel uitvoeren  

**maar**  
- De *output* geeft slechts de laatst gevraagde uitkomst terug


In [14]:
x = 3
y = 5
z = x + y

z
y
x

3

In [15]:
z

8

In [18]:
y

5

### 4.1 Ik wil zo graag méér zien!

De **print** functie

In [29]:
print(haHa, haha_1)
print(haHa)
print(haha_1)

1 2
1
2


In [30]:
tuple_= x, y, z, z
tuple_

(3, 5, 8, 8)

### 4.2 Verder rekenen:

 - Vierkantswortel, sinus, cosinus etc.
  
  Pakket **math** importeren  
  
  
  <span style="color:green">Een pakket vol mathematische functies</span>

In [31]:
import math as mf
mf.sqrt(9)

3.0

In [32]:
mf.sin(1)

0.8414709848078965

In [37]:
mf.cos(1)/mf.sin(1), mf.cos(1), mf.sin(1)

(0.6420926159343308, 0.5403023058681398, 0.8414709848078965)


### 4.3 Hulp bij functies, paketten en andere definities

**Voor als je het even niet meer weet**
    
- help()  
- ?  
- ??  

In [38]:
help(mf.sqrt)

Help on built-in function sqrt in module math:

sqrt(x, /)
    Return the square root of x.



In [63]:
mf?

In [64]:
mf??

## 5. Functies

### 5.1 Kleine machientjes  
  
  
- Aanroepen middels de **naam**  
- *input* invoeren


  **syntax:** naam(input)

In [39]:
print(x)

3


### 5.2 Zelf functies schrijven
Altijd in de volgende vorm:  

def _naam_():  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_actie_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_return_ value

In [1]:
def doe_iets():
    print('wat moet ik doen?')
    return 'gedaan'
    
doe_iets()

wat moet ik doen?


'gedaan'

### 5.3 functie met input
def _naam_(variabel1, variabel2, etc..):  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_actie_  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_return_ value

In [2]:
def persoon(naam, leeftijd):
    print("ik ben", naam, "en ik ben", leeftijd, "jaar oud")
    return True

persoon("timo", "26") # Vul maar eens je eigen naam en leeftijd in

ik ben timo en ik ben 26 jaar oud


True

In [83]:
# Schrijf je eigen definitie die de BTW berekend (9% en 21%) en deze producten. Het totale BTW wordt ge-'returned'. 

appel = 1.5
mes = 9.90

# Eigen code




## 6. Variabelvormen en datastructuren!  

### 6.1 Booleans
  
Wat is **true** en wat is **false**?  
Booleans zijn een bineare opslagvorm.  

In [43]:
True, False

(True, False)

In [44]:
x = True

x

True

In [45]:
y = False

y

False

**True** is eigenlijk hetzelfde als 1  
**False** is eigenlijk hetzelfde als 0

In actie laten we dit zien met vergelijkings operatoren.

### 6.2 Comparison operators

Vergelijkings operatoren

In [90]:
1 == True

True

In [91]:
0 == False

True

In [92]:
1 == 1

True

In [93]:
2 == True

False

In [94]:
False == False

True

### 6.3 Meer vergelijkings operatoren  
  
- Groter dan >
- Kleiner dan <
- Is **niet** gelijk aan !=
- Groter dan of gelijk aan >=
- Kleiner dan of gelijk aan <=

In [103]:
print(3 > 1)
print(3 < 1)
print(3 != 1)
print(3 >= 1)
print(3 <= 1)

True
False
True
True
False


In [102]:
3 >= 3, True >= False, True > False, "Hi" == "Hi", "Hi" == "Hello", "Hello" > "Hi"

(True, True, True, True, False, False)

### 6.4 Numerieke opslag

#### 6.4.1 Integers

Hele getallen

In [5]:
x = 1

In [6]:
x?

#### 6.4.1 Floats:

Floating point numbers: **Decimale getallen**

In [ ]:
t = 1.456

In [ ]:
t?

#### 6.4.3 Charachter strings!

opslag van **tekst**

In [ ]:
haha = 'ik lach me stuk!'
print(haha)

In [ ]:
haha

**print ( . . . )** print de waarde van de variabele  
een gedeclareerde variabele output zichzelf in het geheel

In [47]:
haha_2 = "ik lag me stuk, 'smorgens"

In [48]:
haha_2 = "ik lag me stuk, 's morgens..."
haha_2

"ik lag me stuk, 's morgens..."

In [49]:
print(haha_2)

ik lag me stuk, 's morgens...


### 6.5 Lists

#### 6.5.1 List maken en aanpassen

In [7]:
mijn_LIST = [1,2,3]
print(mijn_LIST)

[1, 2, 3]


In [8]:
[1,2,3]

[1, 2, 3]

In [9]:
mijn_LIST = ['1', 2, 3]
print(mijn_LIST)

['1', 2, 3]


In [10]:
mijn_LIST.append("NEW")
print(mijn_LIST)

['1', 2, 3, 'NEW']


In [11]:
mijn_LIST.append(list(range(100)))
print(mijn_LIST)

['1', 2, 3, 'NEW', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


#### 6.5.2 Waardes terugvinden

In [12]:
mijn_LIST[3]

'NEW'

In [13]:
mijn_LIST[0]

'1'

In [14]:
mijn_LIST[4][40]

40

In [15]:
print(mijn_LIST[4][40:])

[40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [16]:
mijn_LIST[:4]

['1', 2, 3, 'NEW']

In [17]:
print(mijn_LIST[4:])

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


In [18]:
mijn_LIST[4][40] = "target"

In [19]:
print(mijn_LIST[4][8:10])

[8, 9]


### 6.6 Tuples

In [65]:
t = ("a", "b", 'c')

In [66]:
t

('a', 'b', 'c')

In [67]:
t = (1,2,3, 'NEW')

In [68]:
t.index('NEW')

3

In [69]:
t.count(2)

1

### 6.7 Sets

Een gesorteerde lijst van alle unieke ingevoerde waardes

In [75]:
s = {6,8,8,8,8,8,6,6,6,6,3,6,8,6,3,6,8,6,3}

In [76]:
s

{3, 6, 8}

In [77]:
x = {9,9,9,9,9,4,4,4,4,5,5,5,1,1,1,1,6,5,4,8,9,1,1,1}

In [78]:
x

{1, 4, 5, 6, 8, 9}

### 6.8 Dictionairies

**key-value** lists

In [73]:
mijn_Woordenboek = {"key-value":"Opslagparadigma voor waardes opgeslagen per sleutel",
                    "My-Key":"My_Truth!"}

In [74]:
mijn_Woordenboek.keys()

dict_keys(['key-value', 'My-Key'])

In [75]:
mijn_Woordenboek["My-Key"]

'My_Truth!'

In [76]:
mijn_Woordenboek.values()

dict_values(['Opslagparadigma voor waardes opgeslagen per sleutel', 'My_Truth!'])

In [77]:
x = mijn_Woordenboek.items()

In [78]:
x??

In [79]:
mijn_Woordenboek.pop("My-Key")

'My_Truth!'

In [80]:
mijn_Woordenboek

{'key-value': 'Opslagparadigma voor waardes opgeslagen per sleutel'}

### 6.9 Mogelijke extra functionaliteit  

#### 6.9.1 Veelvoorkomende functies
- if ( ), elif ( ), else  
- for ( )  
- while ( ) 
- range ( )
- List comprehension
- map en filter 
- functions & lambda expressions

In [84]:
if(3>2):
    print('3 is bigger than 2')

3 is bigger than 2


In [94]:
lijstje = ['Een', 1, False, 'zin', 'met', int(6.5), 'onnodige', 66, ['tja', 4], 'informatie']
zin = []
for item in lijstje:
    if type(item) == str:
        zin.append(item)
    print(zin)

['Een']
['Een']
['Een']
['Een', 'zin']
['Een', 'zin', 'met']
['Een', 'zin', 'met']
['Een', 'zin', 'met', 'onnodige']
['Een', 'zin', 'met', 'onnodige']
['Een', 'zin', 'met', 'onnodige']
['Een', 'zin', 'met', 'onnodige', 'informatie']


In [111]:
# Oefening, haal nu alle getallen uit het lijstje (als het lukt ook de 4!)

for item in lijstje: 
    # Eigen code
    

#### 6.9.1 Data elementen en indexatie

- Atomische data klassen 
- Indexeren van data in data structuren 
- Data importeren in Python
- Preprocessing

### 6.10 Oefening

In [83]:
# Loop door een dictionary met namen en cijfers. Als een cijfer hoger is dan 
# een 7, sla het persoon dan op in een lijst in het volgende formaat: 
# cijfer_lijst = [(naam, cijfer), (naam, cijfer), etc.. ]
# Denk hierbij aan de functies 'for' en 'if' en 'df.items()'

klas = {'David': 7.4, 'Sergio': 8.1, 'Minoes': 7.7, 'Alexa': 6.999, 'Ceasar': 9.6, 'Billie': 5.4, 'Katja': 8.5}


In [ ]:
# Eigen code





## 7. NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

In [102]:
import numpy as np

## 8. Arrays

### 8.1 Array initieren

In [103]:
mijn_LIST

['1',
 2,
 3,
 'NEW',
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  'target',
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
 

In [104]:
np.array(mijn_LIST)

ValueError: setting an array element with a sequence

In [105]:
Mijn_matrix = [[1,2,3],[1,2,3],[1,2,3]]
Mijn_matrix

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [106]:
np.array(Mijn_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### 8.2 Array slicen en indexeren

In [107]:
Arie = np.arange(0,50,2)

In [108]:
Arie

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [123]:
Arie[8]

16

In [124]:
Arie[6:8]

array([12, 14])

In [125]:
Arie[:8]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [126]:
Arie[8:]

array([16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

### 8.3 Broadcasting

Numpy Arrays verschillen echter wel van Python LISTS:  
**bijvoorbeeld:** broadcasting.  
door indexatie gefilterde waardes gemakkelijk vervangen

In [127]:
Arie[0:8] = False

In [128]:
Arie

array([ 0,  0,  0,  0,  0,  0,  0,  0, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [129]:
Arie[0:8] = Arie[9:].mean()
print(Arie)

[33 33 33 33 33 33 33 33 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [130]:
Stukje_Arie = Arie[0:8]
Stukje_Arie

array([33, 33, 33, 33, 33, 33, 33, 33])

In [131]:
Stukje_Arie[:] = 99

In [132]:
Stukje_Arie

array([99, 99, 99, 99, 99, 99, 99, 99])

In [133]:
Arie[:]

array([99, 99, 99, 99, 99, 99, 99, 99, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

#### <span style="color:green">Conclusie: een variabele een geindexeerd onderdeel van een Array toewijzen lijd tot een *view* van de data, geen compleet nieuwe Array.  </span>
    
Zo worden geheugen-problemen vermeden.


  


In [134]:
np.array??

In [135]:
Arie = np.array((Arie[0:8], Arie[8:16], Arie[16:24]))

In [136]:
Arie

array([[99, 99, 99, 99, 99, 99, 99, 99],
       [16, 18, 20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42, 44, 46]])

In [137]:
Arie[1]

array([16, 18, 20, 22, 24, 26, 28, 30])

In [138]:
Arie[1][0]

16

In [139]:
Arie[1,0]

16

In [140]:
Arie[:2,5:]

array([[99, 99, 99],
       [26, 28, 30]])

In [141]:
Arie[2]

array([32, 34, 36, 38, 40, 42, 44, 46])

In [142]:
Arie[2, :]

array([32, 34, 36, 38, 40, 42, 44, 46])

### 8.4 Array Aritmatiek

**Gevectoriseerde aritmatiek**  

Rekenen met Arie's

In [143]:
Arie = Arie[1]
Arie

array([16, 18, 20, 22, 24, 26, 28, 30])

In [144]:
Arie + 4

array([20, 22, 24, 26, 28, 30, 32, 34])

In [145]:
Arie + Arie

array([32, 36, 40, 44, 48, 52, 56, 60])

In [146]:
Arie - Arie

array([0, 0, 0, 0, 0, 0, 0, 0])

In [147]:
Arie/Arie

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [148]:
1/Arie

array([0.0625    , 0.05555556, 0.05      , 0.04545455, 0.04166667,
       0.03846154, 0.03571429, 0.03333333])

In [149]:
Arie**3

array([ 4096,  5832,  8000, 10648, 13824, 17576, 21952, 27000])

In [150]:
np.sqrt(Arie**3)

array([ 64.        ,  76.36753237,  89.4427191 , 103.18914672,
       117.57550765, 132.57450735, 148.16207342, 164.31676725])

In [151]:
np.exp(Arie)

array([8.88611052e+06, 6.56599691e+07, 4.85165195e+08, 3.58491285e+09,
       2.64891221e+10, 1.95729609e+11, 1.44625706e+12, 1.06864746e+13])

In [152]:
np.max(Arie)   #zelfde als Arrie.max()

30

In [153]:
np.sin(Arie)

array([-0.28790332, -0.75098725,  0.91294525, -0.00885131, -0.90557836,
        0.76255845,  0.27090579, -0.98803162])

In [154]:
np.log(Arie)

array([2.77258872, 2.89037176, 2.99573227, 3.09104245, 3.17805383,
       3.25809654, 3.33220451, 3.40119738])

### 8.5 Numpy array functies   

In [155]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
np.arange(0, 13, 2)

array([ 0,  2,  4,  6,  8, 10, 12])

In [157]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [158]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [159]:
np.ones(3)

array([1., 1., 1.])

In [160]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [161]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [162]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [163]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [164]:
np.random.rand(2)

array([0.57721267, 0.12483107])

In [165]:
np.random.rand(5,5)

array([[0.30101736, 0.42882772, 0.56746755, 0.71150417, 0.52908903],
       [0.70090429, 0.38964825, 0.76533023, 0.8643511 , 0.24603071],
       [0.60377787, 0.54261012, 0.09044776, 0.19940565, 0.29703177],
       [0.60771973, 0.66530161, 0.16824684, 0.20069525, 0.93274009],
       [0.29516981, 0.14691298, 0.96855405, 0.53837415, 0.10016984]])

In [166]:
np.random.randn(5)

array([-0.83309756,  1.49871357,  0.11473296,  0.05048194,  0.83324046])

In [167]:
np.random.randn(5,5)

array([[-0.32665247, -2.02571381,  0.27171238,  0.40376548,  1.4692987 ],
       [ 0.14085352,  0.97410032,  1.32041939, -1.40137135,  1.42825352],
       [ 0.05284289, -0.32574632, -0.85476193,  1.65739858, -0.46380861],
       [-0.63828852,  0.08596133, -0.72139037,  2.3101474 , -0.30664217],
       [ 2.07752457,  0.60217473, -0.26640965,  0.39400292,  0.24125373]])

In [168]:
np.random.randint(90,100)

91

In [169]:
np.random.randint(90,100,10)

array([99, 98, 96, 93, 98, 99, 94, 93, 99, 93])

In [170]:
Arie = np.arange(25)
Ranarie = np.random.randint(0,50,10)
print(Arie)
print(Ranarie)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[33 25 12 11 35 44 21  0 20 15]


In [171]:
Arie.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [172]:
Ranarie.max()

44

In [173]:
Ranarie.argmax()

5

In [174]:
Ranarie.min()

0

In [175]:
Ranarie.argmin()

7

In [176]:
print(Ranarie)

[33 25 12 11 35 44 21  0 20 15]


### 8.6 Shape

Shape is an attribute that arrays have (not a method):

In [177]:
Ranarie.shape

(10,)

In [178]:
Arie.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [179]:
Arie.reshape(5,1)

ValueError: cannot reshape array of size 25 into shape (5,1)

In [180]:
Arie.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [181]:
Arie.reshape(25,1).shape

(25, 1)

In [182]:
Arie

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [183]:
Arie[1].dtype

dtype('int64')

### 8.7 Fancy Indexeren

In [184]:
Arie_2d = np.zeros((10,10))
Arie_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [185]:
Arie_Row_Length = Arie_2d.shape
Arie_Row_Length

(10, 10)

In [186]:
Arie_Row_Length = Arie_2d.shape[1]

In [187]:
print(range(0, Arie_Row_Length))

range(0, 10)


In [188]:
for i in range(Arie_Row_Length):
    Arie_2d[i] = i
    
Arie_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [189]:
Arie_2d[[2,5,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [190]:
Arie_2d[[8,9,1,2]]

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

### 8.8 Gebruik blokhaken voor selectie
Gebasseerd op **vergelijkings operatoren**

In [191]:
Arie

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [192]:
Arie[Arie > 40]

array([], dtype=int64)

In [193]:
Arie_2d[[Arie_2d>4], :]

IndexError: too many indices for array

In [194]:
Arie_2d[Arie_2d > 4]

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 6., 6., 6., 6., 6., 6., 6.,
       6., 6., 6., 7., 7., 7., 7., 7., 7., 7., 7., 7., 7., 8., 8., 8., 8.,
       8., 8., 8., 8., 8., 8., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [195]:
Arie_2d[Arie_2d > 4].reshape(5,10)

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

### 8.9 Oefening

In [240]:
# 1. Bereken het gemiddelde van elke rij en het totale gemiddelde in matrix 
# 2. Sla het op in een dictionary

matrix = np.random.randint(10, size=(10, 10))
dictionary = {"mean_total": 0,
              "mean_rows": 0}

In [74]:
# Eigen code




